# Generated by Django 4.0.4 on 2022-05-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceApp', '0002_staff_can_check_status_staff_can_reset_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='authority',
            field=models.IntegerField(default=10),
        ),
    ]
