# Generated by Django 4.0.4 on 2022-05-23 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceApp', '0003_staff_authority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='staffId',
        ),
    ]