# Generated by Django 4.0.4 on 2022-05-27 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceApp', '0005_staff_can_new_employee_alter_staff_idcard_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
    ]
